# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # left_track_controller:
    #   type: rove_tracks/ChainedController

    # right_track_controller:
    #   type: rove_tracks/ChainedController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    # forward_controller:
    #   type: forward_command_controller/ForwardCommandController 

    flipper_controller:
      type: position_controllers/JointGroupPositionController

# forward_controller:
#   ros__parameters:
#     joints:
#       - track_fl_j
#     interface_name: velocity

flipper_controller:
  ros__parameters:
    joints:
      - flipper_rr_j
      - flipper_fr_j
      - flipper_fl_j
      - flipper_rl_j

diff_drive_controller:
  ros__parameters:
    # left_wheel_names: ["track_l_j"]
    right_wheel_names: ["track_rr_j", "track_fr_j"]
    left_wheel_names: ["track_fl_j", "track_rl_j"]
    # right_wheel_names: ["track_fr_j"]

    wheel_separation: 0.230
    wheel_radius: 0.11

    wheel_separation_multiplier: 10.0
    left_wheel_radius_multiplier: -0.0325
    right_wheel_radius_multiplier: 0.0325

    publish_rate: 20.0
    odom_frame_id: odom
    # allow_multiple_cmd_vel_publishers: true
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 2.0
    # publish_limited_velocity: true
    # publish_cmd: true
    # velocity_rolling_window_size: 10
    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.max_acceleration: 2.0
    linear.x.min_acceleration: -2.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 5.0
    angular.z.min_velocity: -5.0
    angular.z.max_acceleration: 3.0
    angular.z.min_acceleration: -3.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
