/game_controller_node:
  ros__parameters:
    autorepeat_rate: 20.0 # 0 (publish on change)
    coalesce_interval_ms: 50 # 1000ms / 20 (refresh rate in Hz) = 50
    deadzone: 0.2
    sticky_buttons: false

/joy_node:
  ros__parameters:
    autorepeat_rate: 20.0
    coalesce_interval_ms: 50
    deadzone: 0.2
    sticky_buttons: false
