/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: nav_vel
        timeout: 0.5
        priority: 10
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 20
      others:
        topic: cmd_vel
        timeout: 0.5
        priority: 1