// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bridge.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Bridge_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Bridge_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Bridge_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Bridge_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Bridge_2eproto;
class Color;
class ColorDefaultTypeInternal;
extern ColorDefaultTypeInternal _Color_default_instance_;
class DataFrameRequest;
class DataFrameRequestDefaultTypeInternal;
extern DataFrameRequestDefaultTypeInternal _DataFrameRequest_default_instance_;
class DataFrameResponse;
class DataFrameResponseDefaultTypeInternal;
extern DataFrameResponseDefaultTypeInternal _DataFrameResponse_default_instance_;
class RotationXY;
class RotationXYDefaultTypeInternal;
extern RotationXYDefaultTypeInternal _RotationXY_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Color* Arena::CreateMaybeMessage<::Color>(Arena*);
template<> ::DataFrameRequest* Arena::CreateMaybeMessage<::DataFrameRequest>(Arena*);
template<> ::DataFrameResponse* Arena::CreateMaybeMessage<::DataFrameResponse>(Arena*);
template<> ::RotationXY* Arena::CreateMaybeMessage<::RotationXY>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum StatusCode : int {
  IDLE = 0,
  SUCCESS = 1,
  FAILED = 2,
  StatusCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  StatusCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool StatusCode_IsValid(int value);
constexpr StatusCode StatusCode_MIN = IDLE;
constexpr StatusCode StatusCode_MAX = FAILED;
constexpr int StatusCode_ARRAYSIZE = StatusCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatusCode_descriptor();
template<typename T>
inline const std::string& StatusCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, StatusCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function StatusCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    StatusCode_descriptor(), enum_t_value);
}
inline bool StatusCode_Parse(
    const std::string& name, StatusCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<StatusCode>(
    StatusCode_descriptor(), name, value);
}
enum TPVMode : int {
  VELOCITY = 0,
  ANGLE = 1,
  TPVMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TPVMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TPVMode_IsValid(int value);
constexpr TPVMode TPVMode_MIN = VELOCITY;
constexpr TPVMode TPVMode_MAX = ANGLE;
constexpr int TPVMode_ARRAYSIZE = TPVMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TPVMode_descriptor();
template<typename T>
inline const std::string& TPVMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TPVMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TPVMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TPVMode_descriptor(), enum_t_value);
}
inline bool TPVMode_Parse(
    const std::string& name, TPVMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TPVMode>(
    TPVMode_descriptor(), name, value);
}
// ===================================================================

class Color PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Color) */ {
 public:
  inline Color() : Color(nullptr) {};
  virtual ~Color();

  Color(const Color& from);
  Color(Color&& from) noexcept
    : Color() {
    *this = ::std::move(from);
  }

  inline Color& operator=(const Color& from) {
    CopyFrom(from);
    return *this;
  }
  inline Color& operator=(Color&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Color& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Color* internal_default_instance() {
    return reinterpret_cast<const Color*>(
               &_Color_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Color& a, Color& b) {
    a.Swap(&b);
  }
  inline void Swap(Color* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Color* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Color* New() const final {
    return CreateMaybeMessage<Color>(nullptr);
  }

  Color* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Color>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Color& from);
  void MergeFrom(const Color& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Color* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Color";
  }
  protected:
  explicit Color(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Bridge_2eproto);
    return ::descriptor_table_Bridge_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRFieldNumber = 1,
    kGFieldNumber = 2,
    kBFieldNumber = 3,
  };
  // float R = 1;
  void clear_r();
  float r() const;
  void set_r(float value);
  private:
  float _internal_r() const;
  void _internal_set_r(float value);
  public:

  // float G = 2;
  void clear_g();
  float g() const;
  void set_g(float value);
  private:
  float _internal_g() const;
  void _internal_set_g(float value);
  public:

  // float B = 3;
  void clear_b();
  float b() const;
  void set_b(float value);
  private:
  float _internal_b() const;
  void _internal_set_b(float value);
  public:

  // @@protoc_insertion_point(class_scope:Color)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float r_;
  float g_;
  float b_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Bridge_2eproto;
};
// -------------------------------------------------------------------

class RotationXY PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RotationXY) */ {
 public:
  inline RotationXY() : RotationXY(nullptr) {};
  virtual ~RotationXY();

  RotationXY(const RotationXY& from);
  RotationXY(RotationXY&& from) noexcept
    : RotationXY() {
    *this = ::std::move(from);
  }

  inline RotationXY& operator=(const RotationXY& from) {
    CopyFrom(from);
    return *this;
  }
  inline RotationXY& operator=(RotationXY&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RotationXY& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RotationXY* internal_default_instance() {
    return reinterpret_cast<const RotationXY*>(
               &_RotationXY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RotationXY& a, RotationXY& b) {
    a.Swap(&b);
  }
  inline void Swap(RotationXY* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RotationXY* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RotationXY* New() const final {
    return CreateMaybeMessage<RotationXY>(nullptr);
  }

  RotationXY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RotationXY>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RotationXY& from);
  void MergeFrom(const RotationXY& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RotationXY* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RotationXY";
  }
  protected:
  explicit RotationXY(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Bridge_2eproto);
    return ::descriptor_table_Bridge_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float X = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float Y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:RotationXY)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Bridge_2eproto;
};
// -------------------------------------------------------------------

class DataFrameRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DataFrameRequest) */ {
 public:
  inline DataFrameRequest() : DataFrameRequest(nullptr) {};
  virtual ~DataFrameRequest();

  DataFrameRequest(const DataFrameRequest& from);
  DataFrameRequest(DataFrameRequest&& from) noexcept
    : DataFrameRequest() {
    *this = ::std::move(from);
  }

  inline DataFrameRequest& operator=(const DataFrameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataFrameRequest& operator=(DataFrameRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataFrameRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataFrameRequest* internal_default_instance() {
    return reinterpret_cast<const DataFrameRequest*>(
               &_DataFrameRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DataFrameRequest& a, DataFrameRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DataFrameRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataFrameRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataFrameRequest* New() const final {
    return CreateMaybeMessage<DataFrameRequest>(nullptr);
  }

  DataFrameRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataFrameRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataFrameRequest& from);
  void MergeFrom(const DataFrameRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataFrameRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DataFrameRequest";
  }
  protected:
  explicit DataFrameRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Bridge_2eproto);
    return ::descriptor_table_Bridge_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRgbFieldNumber = 1,
    kTpvRotationVelocityFieldNumber = 5,
    kTpvRotationAngleFieldNumber = 6,
    kFrontLightFieldNumber = 2,
    kBackLightFieldNumber = 3,
    kTpvModeFieldNumber = 4,
  };
  // .Color rgb = 1;
  bool has_rgb() const;
  private:
  bool _internal_has_rgb() const;
  public:
  void clear_rgb();
  const ::Color& rgb() const;
  ::Color* release_rgb();
  ::Color* mutable_rgb();
  void set_allocated_rgb(::Color* rgb);
  private:
  const ::Color& _internal_rgb() const;
  ::Color* _internal_mutable_rgb();
  public:
  void unsafe_arena_set_allocated_rgb(
      ::Color* rgb);
  ::Color* unsafe_arena_release_rgb();

  // .RotationXY tpvRotationVelocity = 5;
  bool has_tpvrotationvelocity() const;
  private:
  bool _internal_has_tpvrotationvelocity() const;
  public:
  void clear_tpvrotationvelocity();
  const ::RotationXY& tpvrotationvelocity() const;
  ::RotationXY* release_tpvrotationvelocity();
  ::RotationXY* mutable_tpvrotationvelocity();
  void set_allocated_tpvrotationvelocity(::RotationXY* tpvrotationvelocity);
  private:
  const ::RotationXY& _internal_tpvrotationvelocity() const;
  ::RotationXY* _internal_mutable_tpvrotationvelocity();
  public:
  void unsafe_arena_set_allocated_tpvrotationvelocity(
      ::RotationXY* tpvrotationvelocity);
  ::RotationXY* unsafe_arena_release_tpvrotationvelocity();

  // .RotationXY tpvRotationAngle = 6;
  bool has_tpvrotationangle() const;
  private:
  bool _internal_has_tpvrotationangle() const;
  public:
  void clear_tpvrotationangle();
  const ::RotationXY& tpvrotationangle() const;
  ::RotationXY* release_tpvrotationangle();
  ::RotationXY* mutable_tpvrotationangle();
  void set_allocated_tpvrotationangle(::RotationXY* tpvrotationangle);
  private:
  const ::RotationXY& _internal_tpvrotationangle() const;
  ::RotationXY* _internal_mutable_tpvrotationangle();
  public:
  void unsafe_arena_set_allocated_tpvrotationangle(
      ::RotationXY* tpvrotationangle);
  ::RotationXY* unsafe_arena_release_tpvrotationangle();

  // bool frontLight = 2;
  void clear_frontlight();
  bool frontlight() const;
  void set_frontlight(bool value);
  private:
  bool _internal_frontlight() const;
  void _internal_set_frontlight(bool value);
  public:

  // bool backLight = 3;
  void clear_backlight();
  bool backlight() const;
  void set_backlight(bool value);
  private:
  bool _internal_backlight() const;
  void _internal_set_backlight(bool value);
  public:

  // .TPVMode tpvMode = 4;
  void clear_tpvmode();
  ::TPVMode tpvmode() const;
  void set_tpvmode(::TPVMode value);
  private:
  ::TPVMode _internal_tpvmode() const;
  void _internal_set_tpvmode(::TPVMode value);
  public:

  // @@protoc_insertion_point(class_scope:DataFrameRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Color* rgb_;
  ::RotationXY* tpvrotationvelocity_;
  ::RotationXY* tpvrotationangle_;
  bool frontlight_;
  bool backlight_;
  int tpvmode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Bridge_2eproto;
};
// -------------------------------------------------------------------

class DataFrameResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DataFrameResponse) */ {
 public:
  inline DataFrameResponse() : DataFrameResponse(nullptr) {};
  virtual ~DataFrameResponse();

  DataFrameResponse(const DataFrameResponse& from);
  DataFrameResponse(DataFrameResponse&& from) noexcept
    : DataFrameResponse() {
    *this = ::std::move(from);
  }

  inline DataFrameResponse& operator=(const DataFrameResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataFrameResponse& operator=(DataFrameResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataFrameResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataFrameResponse* internal_default_instance() {
    return reinterpret_cast<const DataFrameResponse*>(
               &_DataFrameResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DataFrameResponse& a, DataFrameResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DataFrameResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataFrameResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataFrameResponse* New() const final {
    return CreateMaybeMessage<DataFrameResponse>(nullptr);
  }

  DataFrameResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataFrameResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataFrameResponse& from);
  void MergeFrom(const DataFrameResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataFrameResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DataFrameResponse";
  }
  protected:
  explicit DataFrameResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Bridge_2eproto);
    return ::descriptor_table_Bridge_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTpvAngleFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // .RotationXY tpvAngle = 2;
  bool has_tpvangle() const;
  private:
  bool _internal_has_tpvangle() const;
  public:
  void clear_tpvangle();
  const ::RotationXY& tpvangle() const;
  ::RotationXY* release_tpvangle();
  ::RotationXY* mutable_tpvangle();
  void set_allocated_tpvangle(::RotationXY* tpvangle);
  private:
  const ::RotationXY& _internal_tpvangle() const;
  ::RotationXY* _internal_mutable_tpvangle();
  public:
  void unsafe_arena_set_allocated_tpvangle(
      ::RotationXY* tpvangle);
  ::RotationXY* unsafe_arena_release_tpvangle();

  // .StatusCode status = 1;
  void clear_status();
  ::StatusCode status() const;
  void set_status(::StatusCode value);
  private:
  ::StatusCode _internal_status() const;
  void _internal_set_status(::StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:DataFrameResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::RotationXY* tpvangle_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Bridge_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Color

// float R = 1;
inline void Color::clear_r() {
  r_ = 0;
}
inline float Color::_internal_r() const {
  return r_;
}
inline float Color::r() const {
  // @@protoc_insertion_point(field_get:Color.R)
  return _internal_r();
}
inline void Color::_internal_set_r(float value) {
  
  r_ = value;
}
inline void Color::set_r(float value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:Color.R)
}

// float G = 2;
inline void Color::clear_g() {
  g_ = 0;
}
inline float Color::_internal_g() const {
  return g_;
}
inline float Color::g() const {
  // @@protoc_insertion_point(field_get:Color.G)
  return _internal_g();
}
inline void Color::_internal_set_g(float value) {
  
  g_ = value;
}
inline void Color::set_g(float value) {
  _internal_set_g(value);
  // @@protoc_insertion_point(field_set:Color.G)
}

// float B = 3;
inline void Color::clear_b() {
  b_ = 0;
}
inline float Color::_internal_b() const {
  return b_;
}
inline float Color::b() const {
  // @@protoc_insertion_point(field_get:Color.B)
  return _internal_b();
}
inline void Color::_internal_set_b(float value) {
  
  b_ = value;
}
inline void Color::set_b(float value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:Color.B)
}

// -------------------------------------------------------------------

// RotationXY

// float X = 1;
inline void RotationXY::clear_x() {
  x_ = 0;
}
inline float RotationXY::_internal_x() const {
  return x_;
}
inline float RotationXY::x() const {
  // @@protoc_insertion_point(field_get:RotationXY.X)
  return _internal_x();
}
inline void RotationXY::_internal_set_x(float value) {
  
  x_ = value;
}
inline void RotationXY::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:RotationXY.X)
}

// float Y = 2;
inline void RotationXY::clear_y() {
  y_ = 0;
}
inline float RotationXY::_internal_y() const {
  return y_;
}
inline float RotationXY::y() const {
  // @@protoc_insertion_point(field_get:RotationXY.Y)
  return _internal_y();
}
inline void RotationXY::_internal_set_y(float value) {
  
  y_ = value;
}
inline void RotationXY::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:RotationXY.Y)
}

// -------------------------------------------------------------------

// DataFrameRequest

// .Color rgb = 1;
inline bool DataFrameRequest::_internal_has_rgb() const {
  return this != internal_default_instance() && rgb_ != nullptr;
}
inline bool DataFrameRequest::has_rgb() const {
  return _internal_has_rgb();
}
inline void DataFrameRequest::clear_rgb() {
  if (GetArena() == nullptr && rgb_ != nullptr) {
    delete rgb_;
  }
  rgb_ = nullptr;
}
inline const ::Color& DataFrameRequest::_internal_rgb() const {
  const ::Color* p = rgb_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Color*>(
      &::_Color_default_instance_);
}
inline const ::Color& DataFrameRequest::rgb() const {
  // @@protoc_insertion_point(field_get:DataFrameRequest.rgb)
  return _internal_rgb();
}
inline void DataFrameRequest::unsafe_arena_set_allocated_rgb(
    ::Color* rgb) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rgb_);
  }
  rgb_ = rgb;
  if (rgb) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataFrameRequest.rgb)
}
inline ::Color* DataFrameRequest::release_rgb() {
  auto temp = unsafe_arena_release_rgb();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Color* DataFrameRequest::unsafe_arena_release_rgb() {
  // @@protoc_insertion_point(field_release:DataFrameRequest.rgb)
  
  ::Color* temp = rgb_;
  rgb_ = nullptr;
  return temp;
}
inline ::Color* DataFrameRequest::_internal_mutable_rgb() {
  
  if (rgb_ == nullptr) {
    auto* p = CreateMaybeMessage<::Color>(GetArena());
    rgb_ = p;
  }
  return rgb_;
}
inline ::Color* DataFrameRequest::mutable_rgb() {
  // @@protoc_insertion_point(field_mutable:DataFrameRequest.rgb)
  return _internal_mutable_rgb();
}
inline void DataFrameRequest::set_allocated_rgb(::Color* rgb) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete rgb_;
  }
  if (rgb) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(rgb);
    if (message_arena != submessage_arena) {
      rgb = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rgb, submessage_arena);
    }
    
  } else {
    
  }
  rgb_ = rgb;
  // @@protoc_insertion_point(field_set_allocated:DataFrameRequest.rgb)
}

// bool frontLight = 2;
inline void DataFrameRequest::clear_frontlight() {
  frontlight_ = false;
}
inline bool DataFrameRequest::_internal_frontlight() const {
  return frontlight_;
}
inline bool DataFrameRequest::frontlight() const {
  // @@protoc_insertion_point(field_get:DataFrameRequest.frontLight)
  return _internal_frontlight();
}
inline void DataFrameRequest::_internal_set_frontlight(bool value) {
  
  frontlight_ = value;
}
inline void DataFrameRequest::set_frontlight(bool value) {
  _internal_set_frontlight(value);
  // @@protoc_insertion_point(field_set:DataFrameRequest.frontLight)
}

// bool backLight = 3;
inline void DataFrameRequest::clear_backlight() {
  backlight_ = false;
}
inline bool DataFrameRequest::_internal_backlight() const {
  return backlight_;
}
inline bool DataFrameRequest::backlight() const {
  // @@protoc_insertion_point(field_get:DataFrameRequest.backLight)
  return _internal_backlight();
}
inline void DataFrameRequest::_internal_set_backlight(bool value) {
  
  backlight_ = value;
}
inline void DataFrameRequest::set_backlight(bool value) {
  _internal_set_backlight(value);
  // @@protoc_insertion_point(field_set:DataFrameRequest.backLight)
}

// .TPVMode tpvMode = 4;
inline void DataFrameRequest::clear_tpvmode() {
  tpvmode_ = 0;
}
inline ::TPVMode DataFrameRequest::_internal_tpvmode() const {
  return static_cast< ::TPVMode >(tpvmode_);
}
inline ::TPVMode DataFrameRequest::tpvmode() const {
  // @@protoc_insertion_point(field_get:DataFrameRequest.tpvMode)
  return _internal_tpvmode();
}
inline void DataFrameRequest::_internal_set_tpvmode(::TPVMode value) {
  
  tpvmode_ = value;
}
inline void DataFrameRequest::set_tpvmode(::TPVMode value) {
  _internal_set_tpvmode(value);
  // @@protoc_insertion_point(field_set:DataFrameRequest.tpvMode)
}

// .RotationXY tpvRotationVelocity = 5;
inline bool DataFrameRequest::_internal_has_tpvrotationvelocity() const {
  return this != internal_default_instance() && tpvrotationvelocity_ != nullptr;
}
inline bool DataFrameRequest::has_tpvrotationvelocity() const {
  return _internal_has_tpvrotationvelocity();
}
inline void DataFrameRequest::clear_tpvrotationvelocity() {
  if (GetArena() == nullptr && tpvrotationvelocity_ != nullptr) {
    delete tpvrotationvelocity_;
  }
  tpvrotationvelocity_ = nullptr;
}
inline const ::RotationXY& DataFrameRequest::_internal_tpvrotationvelocity() const {
  const ::RotationXY* p = tpvrotationvelocity_;
  return p != nullptr ? *p : *reinterpret_cast<const ::RotationXY*>(
      &::_RotationXY_default_instance_);
}
inline const ::RotationXY& DataFrameRequest::tpvrotationvelocity() const {
  // @@protoc_insertion_point(field_get:DataFrameRequest.tpvRotationVelocity)
  return _internal_tpvrotationvelocity();
}
inline void DataFrameRequest::unsafe_arena_set_allocated_tpvrotationvelocity(
    ::RotationXY* tpvrotationvelocity) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(tpvrotationvelocity_);
  }
  tpvrotationvelocity_ = tpvrotationvelocity;
  if (tpvrotationvelocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataFrameRequest.tpvRotationVelocity)
}
inline ::RotationXY* DataFrameRequest::release_tpvrotationvelocity() {
  auto temp = unsafe_arena_release_tpvrotationvelocity();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::RotationXY* DataFrameRequest::unsafe_arena_release_tpvrotationvelocity() {
  // @@protoc_insertion_point(field_release:DataFrameRequest.tpvRotationVelocity)
  
  ::RotationXY* temp = tpvrotationvelocity_;
  tpvrotationvelocity_ = nullptr;
  return temp;
}
inline ::RotationXY* DataFrameRequest::_internal_mutable_tpvrotationvelocity() {
  
  if (tpvrotationvelocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::RotationXY>(GetArena());
    tpvrotationvelocity_ = p;
  }
  return tpvrotationvelocity_;
}
inline ::RotationXY* DataFrameRequest::mutable_tpvrotationvelocity() {
  // @@protoc_insertion_point(field_mutable:DataFrameRequest.tpvRotationVelocity)
  return _internal_mutable_tpvrotationvelocity();
}
inline void DataFrameRequest::set_allocated_tpvrotationvelocity(::RotationXY* tpvrotationvelocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete tpvrotationvelocity_;
  }
  if (tpvrotationvelocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(tpvrotationvelocity);
    if (message_arena != submessage_arena) {
      tpvrotationvelocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, tpvrotationvelocity, submessage_arena);
    }
    
  } else {
    
  }
  tpvrotationvelocity_ = tpvrotationvelocity;
  // @@protoc_insertion_point(field_set_allocated:DataFrameRequest.tpvRotationVelocity)
}

// .RotationXY tpvRotationAngle = 6;
inline bool DataFrameRequest::_internal_has_tpvrotationangle() const {
  return this != internal_default_instance() && tpvrotationangle_ != nullptr;
}
inline bool DataFrameRequest::has_tpvrotationangle() const {
  return _internal_has_tpvrotationangle();
}
inline void DataFrameRequest::clear_tpvrotationangle() {
  if (GetArena() == nullptr && tpvrotationangle_ != nullptr) {
    delete tpvrotationangle_;
  }
  tpvrotationangle_ = nullptr;
}
inline const ::RotationXY& DataFrameRequest::_internal_tpvrotationangle() const {
  const ::RotationXY* p = tpvrotationangle_;
  return p != nullptr ? *p : *reinterpret_cast<const ::RotationXY*>(
      &::_RotationXY_default_instance_);
}
inline const ::RotationXY& DataFrameRequest::tpvrotationangle() const {
  // @@protoc_insertion_point(field_get:DataFrameRequest.tpvRotationAngle)
  return _internal_tpvrotationangle();
}
inline void DataFrameRequest::unsafe_arena_set_allocated_tpvrotationangle(
    ::RotationXY* tpvrotationangle) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(tpvrotationangle_);
  }
  tpvrotationangle_ = tpvrotationangle;
  if (tpvrotationangle) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataFrameRequest.tpvRotationAngle)
}
inline ::RotationXY* DataFrameRequest::release_tpvrotationangle() {
  auto temp = unsafe_arena_release_tpvrotationangle();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::RotationXY* DataFrameRequest::unsafe_arena_release_tpvrotationangle() {
  // @@protoc_insertion_point(field_release:DataFrameRequest.tpvRotationAngle)
  
  ::RotationXY* temp = tpvrotationangle_;
  tpvrotationangle_ = nullptr;
  return temp;
}
inline ::RotationXY* DataFrameRequest::_internal_mutable_tpvrotationangle() {
  
  if (tpvrotationangle_ == nullptr) {
    auto* p = CreateMaybeMessage<::RotationXY>(GetArena());
    tpvrotationangle_ = p;
  }
  return tpvrotationangle_;
}
inline ::RotationXY* DataFrameRequest::mutable_tpvrotationangle() {
  // @@protoc_insertion_point(field_mutable:DataFrameRequest.tpvRotationAngle)
  return _internal_mutable_tpvrotationangle();
}
inline void DataFrameRequest::set_allocated_tpvrotationangle(::RotationXY* tpvrotationangle) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete tpvrotationangle_;
  }
  if (tpvrotationangle) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(tpvrotationangle);
    if (message_arena != submessage_arena) {
      tpvrotationangle = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, tpvrotationangle, submessage_arena);
    }
    
  } else {
    
  }
  tpvrotationangle_ = tpvrotationangle;
  // @@protoc_insertion_point(field_set_allocated:DataFrameRequest.tpvRotationAngle)
}

// -------------------------------------------------------------------

// DataFrameResponse

// .StatusCode status = 1;
inline void DataFrameResponse::clear_status() {
  status_ = 0;
}
inline ::StatusCode DataFrameResponse::_internal_status() const {
  return static_cast< ::StatusCode >(status_);
}
inline ::StatusCode DataFrameResponse::status() const {
  // @@protoc_insertion_point(field_get:DataFrameResponse.status)
  return _internal_status();
}
inline void DataFrameResponse::_internal_set_status(::StatusCode value) {
  
  status_ = value;
}
inline void DataFrameResponse::set_status(::StatusCode value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:DataFrameResponse.status)
}

// .RotationXY tpvAngle = 2;
inline bool DataFrameResponse::_internal_has_tpvangle() const {
  return this != internal_default_instance() && tpvangle_ != nullptr;
}
inline bool DataFrameResponse::has_tpvangle() const {
  return _internal_has_tpvangle();
}
inline void DataFrameResponse::clear_tpvangle() {
  if (GetArena() == nullptr && tpvangle_ != nullptr) {
    delete tpvangle_;
  }
  tpvangle_ = nullptr;
}
inline const ::RotationXY& DataFrameResponse::_internal_tpvangle() const {
  const ::RotationXY* p = tpvangle_;
  return p != nullptr ? *p : *reinterpret_cast<const ::RotationXY*>(
      &::_RotationXY_default_instance_);
}
inline const ::RotationXY& DataFrameResponse::tpvangle() const {
  // @@protoc_insertion_point(field_get:DataFrameResponse.tpvAngle)
  return _internal_tpvangle();
}
inline void DataFrameResponse::unsafe_arena_set_allocated_tpvangle(
    ::RotationXY* tpvangle) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(tpvangle_);
  }
  tpvangle_ = tpvangle;
  if (tpvangle) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataFrameResponse.tpvAngle)
}
inline ::RotationXY* DataFrameResponse::release_tpvangle() {
  auto temp = unsafe_arena_release_tpvangle();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::RotationXY* DataFrameResponse::unsafe_arena_release_tpvangle() {
  // @@protoc_insertion_point(field_release:DataFrameResponse.tpvAngle)
  
  ::RotationXY* temp = tpvangle_;
  tpvangle_ = nullptr;
  return temp;
}
inline ::RotationXY* DataFrameResponse::_internal_mutable_tpvangle() {
  
  if (tpvangle_ == nullptr) {
    auto* p = CreateMaybeMessage<::RotationXY>(GetArena());
    tpvangle_ = p;
  }
  return tpvangle_;
}
inline ::RotationXY* DataFrameResponse::mutable_tpvangle() {
  // @@protoc_insertion_point(field_mutable:DataFrameResponse.tpvAngle)
  return _internal_mutable_tpvangle();
}
inline void DataFrameResponse::set_allocated_tpvangle(::RotationXY* tpvangle) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete tpvangle_;
  }
  if (tpvangle) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(tpvangle);
    if (message_arena != submessage_arena) {
      tpvangle = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, tpvangle, submessage_arena);
    }
    
  } else {
    
  }
  tpvangle_ = tpvangle;
  // @@protoc_insertion_point(field_set_allocated:DataFrameResponse.tpvAngle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::StatusCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::StatusCode>() {
  return ::StatusCode_descriptor();
}
template <> struct is_proto_enum< ::TPVMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TPVMode>() {
  return ::TPVMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Bridge_2eproto
