# Parameters to override zed_wrapper parameters
/**:
  ros__parameters:
    general:
      grab_resolution: "VGA" # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
      pub_frame_rate: 30.0 # frequency of publishing of visual images and depth images
      grab_frame_rate: 30 # ZED SDK internal grabbing rate
      camera_name: "zed"
    mapping:
      mapping_enabled: false # True to enable mapping and fused point cloud pubblication
      resolution: 0.2 # maps resolution in meters [min: 0.01f - max: 0.2f]
      max_mapping_range: 5.0 # maximum depth range while mapping in meters (-1 for automatic calculation) [2.0, 20.0]
      fused_pointcloud_freq: 1.0 # frequency of the publishing of the fused colored point cloud
      clicked_point_topic: "/clicked_point" # Topic published by Rviz when a point of the cloud is clicked. Used for plane detection
      pd_max_distance_threshold: 0.15 # Plane detection: controls the spread of plane by checking the position difference.
      pd_normal_similarity_threshold: 15.0 # Plane detection: controls the spread of plane by checking the angle difference
    depth:
      depth_mode: "PERFORMANCE" # Matches the ZED SDK setting: 'NONE', 'PERFORMANCE', 'QUALITY', 'ULTRA', 'NEURAL', 'NEURAL_PLUS' - Note: if 'NONE' all the modules that requires depth extraction are disabled by default (Pos. Tracking, Obj. Detection, Mapping, ...)
      depth_stabilization: 1 # Forces positional tracking to start if major than 0 - Range: [0,100]
      openni_depth_mode: false # 'false': 32bit float [meters], 'true': 16bit unsigned int [millimeters]
      point_cloud_freq: 30.0 # [DYNAMIC] - frequency of the pointcloud publishing (equal or less to `grab_frame_rate` value)
      depth_confidence: 100 # [DYNAMIC]
      depth_texture_conf: 100 # [DYNAMIC]
      remove_saturated_areas: true # [DYNAMIC]

      min_depth: 0.2 # Min: 0.2, Max: 3.0
      max_depth: 10.0 # Max: 40.0
