# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Bridge.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2

from Common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Bridge.proto',
  package='rove.control_board',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x42ridge.proto\x12\x12rove.control_board\x1a\x0c\x43ommon.proto2u\n\x06\x42ridge\x12\x32\n\x08SetColor\x12\x12.rove.common.Color\x1a\x12.rove.common.Empty\x12\x37\n\rSetFrontLight\x12\x12.rove.common.State\x1a\x12.rove.common.EmptyP\x00\x62\x06proto3'
  ,
  dependencies=[Common__pb2.DESCRIPTOR,],
  public_dependencies=[Common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BRIDGE = _descriptor.ServiceDescriptor(
  name='Bridge',
  full_name='rove.control_board.Bridge',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=50,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetColor',
    full_name='rove.control_board.Bridge.SetColor',
    index=0,
    containing_service=None,
    input_type=Common__pb2._COLOR,
    output_type=Common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetFrontLight',
    full_name='rove.control_board.Bridge.SetFrontLight',
    index=1,
    containing_service=None,
    input_type=Common__pb2._STATE,
    output_type=Common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRIDGE)

DESCRIPTOR.services_by_name['Bridge'] = _BRIDGE

# @@protoc_insertion_point(module_scope)
