# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Bridge.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Bridge.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x42ridge.proto\"(\n\x05\x43olor\x12\t\n\x01R\x18\x01 \x01(\x02\x12\t\n\x01G\x18\x02 \x01(\x02\x12\t\n\x01\x42\x18\x03 \x01(\x02\"\"\n\nRotationXY\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\"\xba\x01\n\x10\x44\x61taFrameRequest\x12\x13\n\x03rgb\x18\x01 \x01(\x0b\x32\x06.Color\x12\x12\n\nfrontLight\x18\x02 \x01(\x08\x12\x11\n\tbackLight\x18\x03 \x01(\x08\x12\x19\n\x07tpvMode\x18\x04 \x01(\x0e\x32\x08.TPVMode\x12(\n\x13tpvRotationVelocity\x18\x05 \x01(\x0b\x32\x0b.RotationXY\x12%\n\x10tpvRotationAngle\x18\x06 \x01(\x0b\x32\x0b.RotationXY\"O\n\x11\x44\x61taFrameResponse\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.StatusCode\x12\x1d\n\x08tpvAngle\x18\x02 \x01(\x0b\x32\x0b.RotationXY*/\n\nStatusCode\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02*\"\n\x07TPVMode\x12\x0c\n\x08VELOCITY\x10\x00\x12\t\n\x05\x41NGLE\x10\x01\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=364,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_TPVMODE = _descriptor.EnumDescriptor(
  name='TPVMode',
  full_name='TPVMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VELOCITY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANGLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=413,
  serialized_end=447,
)
_sym_db.RegisterEnumDescriptor(_TPVMODE)

TPVMode = enum_type_wrapper.EnumTypeWrapper(_TPVMODE)
IDLE = 0
SUCCESS = 1
FAILED = 2
VELOCITY = 0
ANGLE = 1



_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='R', full_name='Color.R', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='G', full_name='Color.G', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='B', full_name='Color.B', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=56,
)


_ROTATIONXY = _descriptor.Descriptor(
  name='RotationXY',
  full_name='RotationXY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='RotationXY.X', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='RotationXY.Y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=92,
)


_DATAFRAMEREQUEST = _descriptor.Descriptor(
  name='DataFrameRequest',
  full_name='DataFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rgb', full_name='DataFrameRequest.rgb', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frontLight', full_name='DataFrameRequest.frontLight', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backLight', full_name='DataFrameRequest.backLight', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tpvMode', full_name='DataFrameRequest.tpvMode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tpvRotationVelocity', full_name='DataFrameRequest.tpvRotationVelocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tpvRotationAngle', full_name='DataFrameRequest.tpvRotationAngle', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=281,
)


_DATAFRAMERESPONSE = _descriptor.Descriptor(
  name='DataFrameResponse',
  full_name='DataFrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='DataFrameResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tpvAngle', full_name='DataFrameResponse.tpvAngle', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=362,
)

_DATAFRAMEREQUEST.fields_by_name['rgb'].message_type = _COLOR
_DATAFRAMEREQUEST.fields_by_name['tpvMode'].enum_type = _TPVMODE
_DATAFRAMEREQUEST.fields_by_name['tpvRotationVelocity'].message_type = _ROTATIONXY
_DATAFRAMEREQUEST.fields_by_name['tpvRotationAngle'].message_type = _ROTATIONXY
_DATAFRAMERESPONSE.fields_by_name['status'].enum_type = _STATUSCODE
_DATAFRAMERESPONSE.fields_by_name['tpvAngle'].message_type = _ROTATIONXY
DESCRIPTOR.message_types_by_name['Color'] = _COLOR
DESCRIPTOR.message_types_by_name['RotationXY'] = _ROTATIONXY
DESCRIPTOR.message_types_by_name['DataFrameRequest'] = _DATAFRAMEREQUEST
DESCRIPTOR.message_types_by_name['DataFrameResponse'] = _DATAFRAMERESPONSE
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.enum_types_by_name['TPVMode'] = _TPVMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), {
  'DESCRIPTOR' : _COLOR,
  '__module__' : 'Bridge_pb2'
  # @@protoc_insertion_point(class_scope:Color)
  })
_sym_db.RegisterMessage(Color)

RotationXY = _reflection.GeneratedProtocolMessageType('RotationXY', (_message.Message,), {
  'DESCRIPTOR' : _ROTATIONXY,
  '__module__' : 'Bridge_pb2'
  # @@protoc_insertion_point(class_scope:RotationXY)
  })
_sym_db.RegisterMessage(RotationXY)

DataFrameRequest = _reflection.GeneratedProtocolMessageType('DataFrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAFRAMEREQUEST,
  '__module__' : 'Bridge_pb2'
  # @@protoc_insertion_point(class_scope:DataFrameRequest)
  })
_sym_db.RegisterMessage(DataFrameRequest)

DataFrameResponse = _reflection.GeneratedProtocolMessageType('DataFrameResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATAFRAMERESPONSE,
  '__module__' : 'Bridge_pb2'
  # @@protoc_insertion_point(class_scope:DataFrameResponse)
  })
_sym_db.RegisterMessage(DataFrameResponse)


# @@protoc_insertion_point(module_scope)
