### ekf config file ###
ekf_filter_node_local:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_tf: true
        map_frame: map              
        odom_frame: odom            
        base_link_frame: base_link
        world_frame: odom

        odom0: /odom
        odom0_config: [false,  false,  false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]
                       
        imu0: /imu
        imu0_config: [false,  false,  false, # x y z
                      true,  true,  true, # roll pitch yaw
                      false,  false,  false, # vx vy vz
                      true,  true,  true, # vroll vpitch vyaw
                      false, false, false] # ax ay az
        imu0_queue_size: 20

        # Add ICP odometry as a new sensor input
        odom1: /icp_odom
        odom1_config: [true,  true,  false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]


ekf_filter_node_global:
    ros__parameters:
        frequency: 30.0
        two_d_mode: false
        publish_tf: true
        map_frame: map              
        odom_frame: odom            
        base_link_frame: base_link
        world_frame: gps

        odom0: /odom
        odom0_config: [true,  true,  false,
                       false, false, false,
                       true, true, false,
                       false, false, false,
                       false, false, false]
                       
        # imu0: /imu
        imu0: /imu
        imu0_config: [false,  false,  false, # x y z
                      false,  false,  true, # roll pitch yaw
                      false,  false,  false, # vx vy vz
                      false,  false,  true, # vroll vpitch vyaw.
                      false, false, false] # ax ay az
        imu0_queue_size: 20

        # description from https://github.com/cra-ros-pkg/robot_localization/blob/ros2/params/ekf.yaml
        # Each sensor reading updates some or all of the filter's state. These options give you greater control over which
        # values from each measurement are fed to the filter. For example, if you have an odometry message as input, but only
        # want to use its Z position value, then set the entire vector to false, except for the third entry. The order of the
        # values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Note that not some message types
        # do not provide some of the state variables estimated by the filter. For example, a TwistWithCovarianceStamped message
        # has no pose information, so the first six values would be meaningless in that case. Each vector defaults to all false
        # if unspecified, effectively making this parameter required for each sensor.
        odom1: /odometry/gps
        odom1_config: [true,  true,  true,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]
