### ekf config file ###
ekf_filter_node_local:
    ros__parameters:
        frequency: 30.0
        two_d_mode: false
        publish_acceleration: true
        publish_tf: true

        map_frame: map              
        odom_frame: odom            
        base_link_frame: base_footprint
        world_frame: odom           

        odom0: /odom
        odom0_config: [true,  true,  true,
                       false, false, true,
                       false, false, false,
                       false, false, true,
                       false, false, false]
                       
        imu0: /imu
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      false, false, false,
                      false, false, false]

ekf_filter_node_global:
    ros__parameters:
        frequency: 30.0
        two_d_mode: false
        publish_acceleration: true
        publish_tf: true

        map_frame: map              
        odom_frame: odom            
        base_link_frame: base_footprint
        world_frame: map           

        odom0: /odom
        odom0_config: [true,  true,  true,
                       false, false, true,
                       false, false, false,
                       false, false, true,
                       false, false, false]
                       
        imu0: /imu
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      false, false, false,
                      false, false, false]

        odom1: /odometry/gps
        odom1_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false 
