@startuml Docker structure

title "Docker Image Dependencies"

rectangle "ros/ros:humble-desktop" as ros
rectangle "clubcapra/rove_base" as base
rectangle "clubcapra/rove_interfaces" as interfaces
rectangle "clubcapra/rove_behavior" as behavior
rectangle "clubcapra/rove_vision" as vision
rectangle "clubcapra/rove_autonomie" as autonomie
rectangle "clubcapra/rove_simulation" as simulation
rectangle "clubcapra/rove_tts" as tts 
rectangle "clubcapra/rove_stt" as stt
rectangle "clubcapra/rove_nlu" as nlu

rectangle "clubcapra/rove_perception" as perception

ros --> base
base --> interfaces
interfaces --> vision
interfaces --> autonomie
interfaces --> behavior
behavior --> tts
behavior --> stt
behavior --> nlu
interfaces --> simulation
interfaces --> perception

@enduml