@startuml Docker structure

title "Docker Image Dependencies"

rectangle "ghcr.io/clubcapra/gazebo:harmonic" as harmonic
rectangle "ros/ros:humble-desktop" as ros_desktop
rectangle "ros/ros:humble-ros-base" as ros_base
rectangle "nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_bcf535ea3b9d16a854aaeb1701ab5a86" as jetson_orin

rectangle "rove-devcontainer" as development_container
rectangle "rove-raspberry-pi" as rpi_container
rectangle "rove-jetson-orin" as jetson_container

development --> ros_desktop
ros_desktop --> harmonic
harmonic --> development_container

"raspberry pi" --> ros_base 
ros_base --> rpi_container

"jeston orin" --> jetson_orin
jetson_orin --> jetson_container

@enduml
