name: ROS2 rove build
run-name: ${{ github.actor }} is working on ROS2 rove build
on: [push]
jobs:
  Build_rove:
    runs-on: [self-hosted, linux, docker]
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Build docker compose
      run: |
        docker compose build --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
        docker compose run devcontainer bash -c "colcon build"

