name: ROS2 rove build
run-name: ${{ github.actor }} is working on ROS2 rove build
on: [push]
jobs:
  Build_rove:
    runs-on: [caprabuilder]
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Build docker compose
      run: |
        docker compose run --user root devcontainer bash -c "colcon build"

